### ISSUE TITLE
Get Consistency Group missing from API Library

### ISSUE THREAD

**Issue by phspies** [DimensionDataCBUSydney/Compute.Api.Client#2]
It seems the library is missing a API call:
Note that it is more efficient to use Get Consistency Group than List Consistency Groups (filtered by id)
if you wish to retrieve status or details of a single Consistency Group.

```
https://<Cloud API URL>/caas/2.3/{orgid}/
consistencyGroup/consistencyGroup/{consistency-group-id}
```

**Comment by BenObermayer** [comment]
We'll take a look and fix.

**Comment by BenObermayer** [comment]
This is now fixed.

**Comment by Saanch** [comment]
Added the api call.
