### ISSUE TITLE
Getting started issue

### ISSUE THREAD

**Issue by benwelker** [DimensionDataCBUSydney/Compute.Api.Client#4]
Trying to use the basic getting started example from the documentation on DD website.  I get the following error, and am unsure if it's pointing to an issue on my side or DD side.

`System.InvalidOperationException: There is an error in XML document (1, 46). ---> System.InvalidOperationException: <user xmlns='urn:didata.com:api:cloud:types'> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderAccount.Read4_Account()
   --- End of inner exception stack trace ---`

I am literally copy/pasting the code from the getting started example, and modifying the username and password.  So something tells me the documentation may not be updated...

**Comment by tintoy** [comment]
Hi - would you mind pasting the example code you're using here?

**Comment by benwelker** [comment]
Sure thing, for reference: [DD Getting Started example](https://docs.mcp-services.net/display/CCS/Getting+started)

First I created a console app project, and made a new class "TestClient".  I copied this code directly into my project from the link above, and modified the KnownApiRegion to NorthAmerica_NA and the username and password of course.  I also added the Console.WriteList(ex) in the MainAsync() method to see if anything was being caught which is then where I see the error in my previous post.  (Sorry about formatting, I'm still relatively new to GitHub...)

```csharp
using System.Linq;
using System.Net;
using System.Threading.Tasks;
 
namespace DD.Cloud.Examples.ApiClient
{
    using DD.CBU.Compute.Api.Client;
    using DD.CBU.Compute.Api.Client.Interfaces;
    using DD.CBU.Compute.Api.Contracts.Directory;
 
    public class TestClient
    {
        private IComputeApiClient _apiClient;
        private ICredentials _credentials = new NetworkCredential("myuser", "mypassword");
        private KnownApiRegion _targetRegion = KnownApiRegion.NorthAmerica_NA;
        private KnownApiVendor _targetVendor = KnownApiVendor.DimensionData;
 
        public TestClient()
        {
            _apiClient = ComputeApiClient.GetComputeApiClient(_targetVendor, _targetRegion, _credentials);
        }
 
        public async Task<string[]> GetServerNames()
        {
            // Login
            IAccount myAccount = await _apiClient.Login();
            // Get all of the servers
            var servers = await _apiClient.ServerManagement.Server.GetServersPaginated();
            // Return all of the server names
            return servers.items.Select(server => server.name).ToArray();           
        }
    }
}
```

Then I made my Program.cs file match this (sorry formatting isn't working here at all for some reason.)

```csharp
using System;
using System.Threading.Tasks;
namespace DD.Cloud.Examples.ApiClient
{
    class Program
    {
        static void Main(string[] args)
        {
            MainAsync().Wait();
            Console.ReadKey();
        }
        static async Task<string[]> MainAsync()
        {
            try
            {
                TestClient cli = new TestClient();
                return await cli.GetServerNames();
            }
            catch (Exception ex)
            {
                // Handle Exception
                Console.WriteLine(ex);
                return new string[] { };
            }
        }
    }
}
```

**Comment by tintoy** [comment]
I tried the code above, and don't get an error; what version of the `DD.CBU.Compute.Api.Client` NuGet package are you using? I'm using ` 3.6.43`, but I did change one line because I got a warning about the `Login` method being obsolete:

```csharp
IUser myUser = await _apiClient.LoginAsync();
```

I'll have a chat to the folks who maintain this library and get them to update the sample code.

BTW, the trick to formatting is to use a triple-tick followed by language name, e.g.

\`\`\`csharp
xxx
\`\`\`

(hope you don't mind, but I edited your comments to add this formatting)

**Comment by benwelker** [comment]
Thanks for the tip, I guess I was assuming changing Login to LoginAsync would have caused issues since even though it was marked "obsolete" the documentation was still using it.  After making that change, I'm not getting the error anymore.  Looks like since I started down this path there's a new stable version which I'll have to update to (the one you posted [3.6.43]) as I was using 3.5.31.

Would still be nice if they updated their documentation, but that looks like it will do it for me.  Thanks!

**Comment by tintoy** [comment]
No worries, sorry for the inconvenience. I've updated the docs and notified the project maintainers so hopefully they'll stay up to date now :)
